# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from Crypto.Cipher import AES, PKCS1_v1_5
from Crypto.PublicKey import RSA
from Crypto.Random import get_random_bytes
from Crypto.Util.Padding import pad
from concurrent.futures import ThreadPoolExecutor
from datetime import timedelta
from typing import Any
from typing_extensions import Self
from urllib.parse import quote
import aiohttp
import argparse
import asyncio
import base64
import hashlib
import json
import marshal
import ntplib
import os
import ping3
import random
import re
import requests
import string
import subprocess
import sys
import time
import urllib
import zlib

__ALL__ = []
SUCCESS = 0
IN_RUNNING_ASCII_BIN = []
MY = ''
ascii_lower_bin6 = []
ascii_lower_bin7 = []
ascii_upper_bin6 = []
ascii_upper_bin7 = []
ascii_bin_mix6 = []
ascii_bin_mix7 = []
def clear() -> Any:
    ...

w = '\x1b[1;00m'
g = '\x1b[1;32m'
y = '\x1b[1;33m'
r = '\x1b[1;31m'
b = '\x1b[1;34m'
def Line() -> Any:
    ...

def Logo() -> Any:
    ...

def feature() -> Any:
    ...

headers = {'authority': 'portal-as.ruijienetworks.com', 'accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7', 'accept-language': 'en-US,en;q=0.9', 'referer': session_url, 'sec-ch-ua': '"Chromium";v="139", "Not;A=Brand";v="99"', 'sec-ch-ua-mobile': '?1', 'sec-ch-ua-platform': '"Android"', 'sec-fetch-dest': 'document', 'sec-fetch-mode': 'navigate', 'sec-fetch-site': 'same-origin', 'upgrade-insecure-requests': '1', 'user-agent': 'Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Mobile Safari/537.36'}
class InternetAccess:
    def __init__(self: Self) -> None: ...
    def get_random_code(self: Self) -> Any: ...
    def get_ping(self: Self, ping: Any) -> Any: ...

data = {'accessCode': voucher, 'sessionId': session_id, 'apiVersion': 1}
headers = {'authority': 'portal-as.ruijienetworks.com', 'accept': '*/*', 'accept-language': 'en-US,en;q=0.9', 'content-type': 'application/json', 'origin': 'https://portal-as.ruijienetworks.com', 'referer': f'https://portal-as.ruijienetworks.com/download/static/maccauth/src/index.html?RES=./../expand/res/mrlev58jlgslg49ervu&IS_EG=0&sessionId={session_id}', 'sec-ch-ua': '"Chromium";v="139", "Not;A=Brand";v="99"', 'sec-ch-ua-mobile': '?1', 'sec-ch-ua-platform': '"Android"', 'sec-fetch-dest': 'empty', 'sec-fetch-mode': 'cors', 'sec-fetch-site': 'same-origin', 'user-agent': f'Mozilla/5.0 (Linux; Android 12; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Mobile Safari/537.36'}
response = await req.text()
def write_file(file: Any, data: Any) -> Any:
    ...

def ascii_generator(mode: Any, length: Any) -> Any:
    ...

def digit_generator(length: Any) -> Any:
    ...

class VoucherCode:
    def __init__(self: Self, mode: Any, length: Any, speed: Any, tasks: Any, debug: Any) -> None: ...
    def remove_already_checked(self: Self, vouchers: Any) -> Any: ...

class RecheckVoucher:
    def __init__(self: Self) -> None: ...

class Setup:
    def __init__(self: Self) -> None: ...
    def set(self: Self) -> Any: ...
    def unbind(self: Self) -> Any: ...
    def username_get(self: Self) -> Any: ...
    def get_online_info(self: Self, username: Any) -> Any: ...
    def arrange_data(self: Self, info: Any) -> Any: ...
    def get_data(self: Self) -> Any: ...
    def extract_chap(self: Self, data: Any) -> Any: ...
    def encrypt_cryptojs(self: Self, auth: Any, enc_key: Any) -> Any: ...
    def get_auth(self: Self, username: Any) -> Any: ...
    def logout(self: Self, data: Any, username: Any) -> Any: ...

def get_current_time() -> Any:
    ...

def get_random_string(length: Any) -> Any:
    ...

github = 'https://raw.githubusercontent.com/win462550-ui/wintunmhwe/main/auth.json'
response = await req.text()
response = None
def check_key_expiration(expiration_time: Any, current_time: Any) -> Any:
    ...

def get_uid() -> Any:
    ...

class Security:
    def __init__(self: Self) -> None: ...
    def check_key(self: Self) -> Any: ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import os
import typing
import re
import http
import http.cookies
import functools
import struct
import aiohttp._websocket.mask
import json
import enum
import asyncio
import builtins
import collections
import collections.deque
import random
import sys
import logging
import socket
import abc
import collections.abc
import multidict
import multidict.CIMultiDict
import yarl
import yarl.URL
import base64
import hashlib
import traceback
import warnings
import contextlib
import types
import attr
import multidict.MultiDict
import multidict.MultiDictProxy
import multidict.istr
import multidict.MultiMapping
import ssl
import time
import codecs
import io
import multidict.CIMultiDictProxy
import zlib
import concurrent
import concurrent.futures
import concurrent.futures.Executor
import brotlicffi
import brotli
import backports
import backports.zstd
import collections.OrderedDict
import collections.defaultdict
import http.HTTPStatus
import itertools
import aiohappyeyeballs
import aiohappyeyeballs.AddrInfoType
import aiohappyeyeballs.SocketFactoryType
import calendar
import datetime
import heapq
import pathlib
import pickle
import urllib
import urllib.parse
import binascii
import inspect
import netrc
import platform
import weakref
import collections.namedtuple
import email
import email.message
import email.parser
import email.policy
import email.utils
import math
import pathlib.Path
import urllib.request
import propcache
import propcache.api
import aiohttp.__version__
import textwrap
import string
import aiohttp._http_parser
import aiohttp._http_writer
import uuid
import mimetypes
import pytest
import uvloop
import aiodns
import gc
import ipaddress
import unittest
import unittest.mock
import aiosignal
import aiosignal.Signal
import aiohttp.ClientSession
import yarl.Query
import argparse
import importlib
import frozenlist
import frozenlist.FrozenList
import stat
import asyncio.streams
import html
import html.escape
import logging.Logger
import propcache.under_cached_property
import tempfile
import signal
import keyword
import yarl.__version__
import gunicorn
import gunicorn.config
import gunicorn.workers
import charset_normalizer
import charset_normalizer.__version__
import chardet
import cryptography
import logging.NullHandler
import posixpath
import urllib3.util.Timeout
import urllib3.util.parse_url
import threading
import certifi
import certifi.where
import urllib3.__version__
import simplejson
import json.JSONDecodeError
import http.cookiejar
import copy
import dummy_threading
import idna
import OpenSSL
import encodings
import encodings.idna
import zipfile
import urllib3.util.make_headers
import ping3
import ntplib
import marshal
import subprocess
import Crypto
import Crypto.PublicKey
import Crypto.PublicKey.RSA
import Crypto.Util
import Crypto.Util.Padding
import Crypto.Cipher
import Crypto.Cipher.AES
import Crypto.Cipher.PKCS1_v1_5
import Crypto.Random
import Crypto.Random.get_random_bytes
import concurrent.futures.ThreadPoolExecutor
import __future__
import http.client
import urllib3.util.SKIP_HEADER
import urllib3.util.SKIPPABLE_HEADERS
import errno
import queue
import importlib.resources
import js
import pyodide
import pyodide.ffi
import dataclasses
import OpenSSL.SSL
import cryptography.x509
import cryptography.x509.extensions
import OpenSSL.crypto
import socks
import email.errors
import importlib.metadata
import h2
import h2.config
import h2.connection
import h2.events
import hmac
import select